### ISSUE TITLE
Not sure what word is amiss without coloring

### ISSUE THREAD

**Issue by kvz** [lukeapage/node-markdown-spellcheck#45] opened 2015-09-15 15:07 UTC
Minor issue, and not sure how to fix, but just something I noticed.

When running in CI, I can't turn on colors. But without them, it's a bit guesswork which word triggered the fail:

![](https://dl.dropboxusercontent.com/s/yhekhdm70i8oabc/2015-09-15%20at%2017.06%202x.png?dl=0)

**Comment by lukeapage** [comment] 2015-09-15 18:33
duplicate of #36

**Closed by lukeapage** 2015-09-15 18:33 UTC
